// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCs46WNH-iYeQBEpGaZdsxcamnOBZOGX8',
    appId: '1:612967236484:web:7bec151841fa3bf5de13d1',
    messagingSenderId: '612967236484',
    projectId: 'chat-app-79cd1',
    authDomain: 'chat-app-79cd1.firebaseapp.com',
    storageBucket: 'chat-app-79cd1.appspot.com',
    measurementId: 'G-CPYQFKV1WC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6NVMs-dLda0fMlmuQCFL-H_n_gp7sp7g',
    appId: '1:612967236484:android:ee41162dd4df8d58de13d1',
    messagingSenderId: '612967236484',
    projectId: 'chat-app-79cd1',
    storageBucket: 'chat-app-79cd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPFcd8LeUha-Joi9ty39Aq002cgHgjInM',
    appId: '1:612967236484:ios:295c43d01250e9b9de13d1',
    messagingSenderId: '612967236484',
    projectId: 'chat-app-79cd1',
    storageBucket: 'chat-app-79cd1.appspot.com',
    iosClientId: '612967236484-6fojb7je55966g80g9s9qtjihvaqtbuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPFcd8LeUha-Joi9ty39Aq002cgHgjInM',
    appId: '1:612967236484:ios:295c43d01250e9b9de13d1',
    messagingSenderId: '612967236484',
    projectId: 'chat-app-79cd1',
    storageBucket: 'chat-app-79cd1.appspot.com',
    iosClientId: '612967236484-6fojb7je55966g80g9s9qtjihvaqtbuo.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
